version: '3.9'
services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: >
      sh -c "sleep 15 && npm run start:dev api-gateway"
    depends_on:
      - users
      - actions-history
      - rabbitmq
      - db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '5003:5000'
  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: >
      sh -c "sleep 15 && npm run start:dev users"
    env_file:
      - ./apps/users/.env
    depends_on:
      - db
      - rabbitmq
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  actions-history:
    build:
      context: .
      dockerfile: ./apps/actions-history/Dockerfile
      target: development
    command: npm run start:dev actions-history
    ports:
      - '3002:3002'
    env_file:
      - ./apps/actions-history/.env
    depends_on:
      - db
      - rabbitmq
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_module
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    networks:
      - default
  rabbitmq:
    image: rabbitmq:3.10.7-management
    ports:
      - 5672:5672
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=kino
    ports:
      - 5432:5432
